
    [build]
    target = "riscv64imac-unknown-none-elf"

    [target.'cfg(target_os = "none")']
    runner = "./script/riscv64/riscv64_test.sh"
    rustflags = [
        "-Clink-arg=-Tsel4_ipc/linker.ld",
        "-Cforce-frame-pointers=yes",
        '--cfg=board="qemu"',
    ]
    